bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: GXL3ILkRBw0ymlnhQyLWR2cgYv5w8Ibt05Nvg2sVQ84BpJ4mf3QHalEg3hcu5gk6ohPwV4PxZp9rItPQ80PPXa/5TB3tdWk5jX9FPaCETKmxNejTUqWfRXn+2v86C2eKf//mADX3tw0AsKM0awOHWa4+nPvReJdyqS0CogeXuR9a+tCuTIgZYaXNC7iQkfel/0th+rgvHhrI84rdA4TJfXFgtoKsfqGFzOQNe/vmubdS0Rwgzpf0bHoQ7JY3zD62bDyxuv3Y+9hYMJT253naZ3RbeBbfv4Mjr/CGjikDreRWWcSNkSVaEuXyRJ0bkrrfC8FTGuOXi1opu2FOTjdoTiVrIcZVGpXexExRb0FstPnxoTvahBrB4ycpEY0Zz67ghRQPIF/WA97IE/pMlVatbmEXsBoNm3UTS+QBLq4fOZBYBplHM0yY+5ZndvoFlcaMRP7g3WivIIUXI5Th+7Y3xT6pWtmY+iIU6ie/vcjjkjt8W3XdD5RM5UXiPJ0op1pOs0otnbHaipmygHslSmG0RlnTjxKt+bxJEgRzY6g5hOXU4rL7dvbC9ZZcQJFWQmB2AfTmJ3AEUQ663EOQ/0LHMqL6M+hEeH4NHLqmLhXgQLZPfWsVJYUT4Ysnv+6iGBfcrQprOQkiPAyCulIlVf9XOBXoxXasE5Af513LcpICvfE=
conda_forge_output_validation: false
